name: Code Auto-Format

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  format-code:

    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Free up disk space on runner
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/.ghcup

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache dependencies
        uses: actions/cache@v4.3.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install .[dev]

      - name: Remove unused imports and variables
        run: |
          autoflake --in-place --recursive \
            --remove-all-unused-imports \
            --remove-unused-variables \
            --expand-star-imports \
            --exclude=__init__.py .
        continue-on-error: true

      - name: Sort imports with isort
        run: isort .

      - name: Run formatter (Black)
        run: black .

      - name: Create Pull Request
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Chore: Auto-format code with isort and black"
          title: "Fixes: Apply automatic code formatting"
          body: |
            This PR was auto-generated by a GitHub Action to apply `isort` and `black` code formatting.
            Please review and merge to maintain a consistent code style.
          branch: "auto-formatting/${{ github.ref_name }}"
          labels: "automated pr, style"
          assignees: "${{ github.actor }}"